# Generated by Django 3.1.5 on 2021-01-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
